# Generated by Django 3.1.3 on 2022-02-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full_Time', 'Full_Time'), ('Part_Time', 'Part_Time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
