# Generated by Django 3.1.3 on 2022-02-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20220224_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('Femel', 'Femel'), ('Male', 'Male'), ('Prefer not answer', 'Prefer not to answer')], max_length=50),
        ),
    ]
